# Generated by Django 2.1.4 on 2018-12-08 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailappmodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 8, 13, 16, 46, 497354)),
        ),
    ]
